[[mgr.prepend_keymap]]
on = "<C-o>"
run = 'shell --block -- ~/.config/yazi/scripts/open-with.sh "%h"'
desc = "Open the hovered item with"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Smart enter"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "R"
run = "rename --empty=stem --cursor=start"
desc = "Rename from scratch"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "cd ~/.local/share/Trash/files/"
desc = "Go Trash"

[[mgr.prepend_keymap]]
on = [ "g", "D" ]
run = "cd ~/Documents/"
desc = "Go ~/Documents"

[[mgr.prepend_keymap]]
on = [ "g", "y" ]
run = "cd ~/ywdsem/"
desc = "Go ywdsem"
