[mgr]
show_hidden = true
sort_by = "natural"
linemode = "size"

[opener]
open = [
  { run = 'xdg-open "$@"', orphan = true, desc = "Open" },
]
edit = [
  { run = 'nvim "$@"', block = true },
  { run = 'code "$@"', orphan = true },
]
play = [
  { run = 'xdg-open "$@"', orphan = true, desc = "Open" },
]

[open]

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"
